name: Run UI Tests on iOS Simulator

on:
  [ workflow_dispatch ]

jobs:
  ui-tests:
    runs-on: macos-14 # Adjust macOS version to match your needs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Xcode Tools
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.app # Specify Xcode version
          xcodebuild -version
          xcrun simctl list runtimes
